// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import "time"

type CallInput struct {
	Cmd  string   `json:"cmd"`
	Args []string `json:"args"`
}

type Result struct {
	ID     string    `json:"id"`
	Cmd    string    `json:"cmd"`
	Args   []string  `json:"args"`
	Stdout []string  `json:"stdout"`
	Stderr []string  `json:"stderr"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type User struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Token  *string `json:"token"`
	Active bool    `json:"active"`
}
